# Generated by Django 4.2 on 2024-08-11 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_alter_all_type_clothes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_type_clothes',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clothes.category'),
        ),
    ]
