# Generated by Django 4.2 on 2024-08-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0008_alter_all_type_clothes_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='all_type_clothes',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_date']},
        ),
    ]
