# Generated by Django 4.2 on 2024-08-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0010_alter_all_type_clothes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_type_clothes',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
