# Generated by Django 4.2 on 2024-08-28 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0011_alter_all_type_clothes_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name_category',
        ),
    ]
