# Generated by Django 4.2 on 2024-08-25 19:33

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='blog/default.jpg', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='blog/'),
        ),
    ]
